apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-lambda-template
  title: Criar uma AWS Lambda
  description: Template para criar um repositório e configurar uma AWS Lambda

spec:
  owner: equipe-dev
  type: service  # <-- Adicione esta linha para corrigir o erro
  parameters:
    - title: Configuração da Lambda
      required:
        - owner
        - repo
        - runtime
      properties:
        owner:
          title: Organização ou Usuário no GitHub
          type: string
          description: Nome da organização ou usuário dono do repositório
        repo:
          title: Nome do Repositório
          type: string
          description: Nome do novo repositório a ser criado
        runtime:
          title: Runtime da Lambda
          type: string
          enum:
            - nodejs18.x
            - python3.9
            - python3.11
            - java17
          description: Escolha o runtime para a AWS Lambda

  steps:
    - id: create-repo
      name: Criando repositório no GitHub
      action: github:repo:create
      input:
        repoUrl: github.com/${{ parameters.owner }}/${{ parameters.repo }}
        description: "Repositório criado pelo Backstage para uma AWS Lambda"
        visibility: public
